services:
  user-db:
    # image: postgres:latest # Linux OS + PostgreSQL (latest version)
    image: postgres:latest

    container_name: user-db-container # Name of the Docker Container

    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}

    ports:
      - "${USER_DB_PORT}:5432" # Map the host port to the port of the Docker Container
      
  news-db:
    image: postgres:latest
    container_name: news-db-container
    environment:
      POSTGRES_USER: ${NEWS_DB_USER}
      POSTGRES_PASSWORD: ${NEWS_DB_PASSWORD}
      POSTGRES_DB: ${NEWS_DB_NAME}
    ports:
      - "${NEWS_DB_PORT}:5432" # Maps localhost:5433 to container:5432